name: E-Skate
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2238
title: MKV E-Skate log
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8ecf3'
    - '#0f1417'
    - '#02a5e8'
    - '#0068ad'
    - '#5acefc'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
