name: MKV E-Skate log
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2238
title: MKV E-Skate log
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#151419'
    - '#f1b060'
    - '#fc4348'
    - '#5b754f'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
