name: mkv-electric-skate
favicon: null
layout_spectrum: 0.19152116845361888
typography_spectrum: 0.18116553220897913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#151419'
    - '#f1b060'
    - '#fc4348'
    - '#5b754f'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
